language: node_js
node_js:
  - "5"
before_install:
  - '[ "${TRAVIS_NODE_VERSION}" != "0.8" ] || npm install -g npm@1.4.28'
  - npm install -g npm@latest
install:
  - npm install
script: npm run test
