name: Lint

on:
  pull_request:
    paths:
      - 'src/scripts/**'
      - package-lock.json
      - '.browserslistrc'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install dependencies
        run: npm install --no-optional --no-audit --ignore-scripts
        env:
          HUSKY_SKIP_INSTALL: true

      - name: run eslint
        run: |
          CHANGED_TS=$(git --no-pager diff --name-only ..origin/master | grep '^src\/scripts\/.*\.ts$' | paste -sd " " -)
          if [[ -z $(sed -e 's/[[:space:]]*$//' <<<${CHANGED_TS}) ]]; then CHANGED_TS="src/scripts"; fi
          echo $CHANGED_TS
          node node_modules/eslint/bin/eslint.js $CHANGED_TS
