name: Unit Tests

on:
  pull_request:
    paths:
      - 'src/scripts/**'
      - package-lock.json
      - '.browserslistrc'

jobs:
  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install dependencies
        run: npm install --no-optional --no-audit --ignore-scripts
        env:
          HUSKY_SKIP_INSTALL: true

      - run: npm run test
        env:
          FORCE_COLOR: 2
